#ifndef _KEYBOARD_H_
#define _KEYBOARD_H_

#define SYS_KEY_ESC               KEY_ESC     /* keyboard scan codes  */
#define SYS_KEY_1                 KEY_1 
#define SYS_KEY_2                 KEY_2 
#define SYS_KEY_3                 KEY_3
#define SYS_KEY_4                 KEY_4
#define SYS_KEY_5                 KEY_5
#define SYS_KEY_6                 KEY_6
#define SYS_KEY_7                 KEY_7
#define SYS_KEY_8                 KEY_8
#define SYS_KEY_9                 KEY_9
#define SYS_KEY_0                 KEY_0
#define SYS_KEY_MINUS             KEY_MINUS
#define SYS_KEY_EQUALS            KEY_EQUALS
#define SYS_KEY_BACKSPACE         KEY_BACKSPACE
#define SYS_KEY_TAB               KEY_TAB
#define SYS_KEY_Q                 KEY_Q
#define SYS_KEY_W                 KEY_W
#define SYS_KEY_E                 KEY_E
#define SYS_KEY_R                 KEY_R
#define SYS_KEY_T                 KEY_T
#define SYS_KEY_Y                 KEY_Y
#define SYS_KEY_U                 KEY_U
#define SYS_KEY_I                 KEY_I
#define SYS_KEY_O                 KEY_O
#define SYS_KEY_P                 KEY_P
#define SYS_KEY_OPENBRACE         KEY_OPENBRACE
#define SYS_KEY_CLOSEBRACE        KEY_CLOSEBRACE
#define SYS_KEY_ENTER             KEY_ENTER
#define SYS_KEY_CONTROL           KEY_CONTROL
#define SYS_KEY_LCONTROL          KEY_LCONTROL
#define SYS_KEY_A                 KEY_A
#define SYS_KEY_S                 KEY_S
#define SYS_KEY_D                 KEY_D
#define SYS_KEY_F                 KEY_F
#define SYS_KEY_G                 KEY_G
#define SYS_KEY_H                 KEY_H
#define SYS_KEY_J                 KEY_J
#define SYS_KEY_K                 KEY_K
#define SYS_KEY_L                 KEY_L
#define SYS_KEY_COLON             KEY_COLON
#define SYS_KEY_QUOTE             KEY_QUOTE
#define SYS_KEY_TILDE             KEY_TILDE
#define SYS_KEY_LSHIFT            KEY_LSHIFT
#define SYS_KEY_BACKSLASH         KEY_BACKSLASH
#define SYS_KEY_Z                 KEY_Z
#define SYS_KEY_X                 KEY_X
#define SYS_KEY_C                 KEY_C
#define SYS_KEY_V                 KEY_V
#define SYS_KEY_B                 KEY_B
#define SYS_KEY_N                 KEY_N
#define SYS_KEY_M                 KEY_M
#define SYS_KEY_COMMA             KEY_COMMA
#define SYS_KEY_STOP              KEY_STOP
#define SYS_KEY_SLASH             KEY_SLASH
#define SYS_KEY_RSHIFT            KEY_RSHIFT
#define SYS_KEY_ASTERISK          KEY_ASTERISK
#define SYS_KEY_ALT               KEY_ALT
#define SYS_KEY_SPACE             KEY_SPACE
#define SYS_KEY_CAPSLOCK          KEY_CAPSLOCK
#define SYS_KEY_F1                KEY_F1
#define SYS_KEY_F2                KEY_F2
#define SYS_KEY_F3                KEY_F3
#define SYS_KEY_F4                KEY_F4
#define SYS_KEY_F5                KEY_F5
#define SYS_KEY_F6                KEY_F6
#define SYS_KEY_F7                65
#define SYS_KEY_F8                66
#define SYS_KEY_F9                67
#define SYS_KEY_F10               68
#define SYS_KEY_NUMLOCK           69
#define SYS_KEY_SCRLOCK           70
#define SYS_KEY_HOME              71
#define SYS_KEY_UP                KEY_UP
#define SYS_KEY_PGUP              73
#define SYS_KEY_MINUS_PAD         74
#define SYS_KEY_LEFT              KEY_LEFT
#define SYS_KEY_5_PAD             76
#define SYS_KEY_RIGHT             KEY_RIGHT
#define SYS_KEY_PLUS_PAD          KEY_PLUS_PAD
#define SYS_KEY_END               79
#define SYS_KEY_DOWN              KEY_DOWN
#define SYS_KEY_PGDN              81
#define SYS_KEY_INSERT            82
#define SYS_KEY_DEL               83
#define SYS_KEY_PRTSCR            84
#define SYS_KEY_F11               87
#define SYS_KEY_F12               88
#define SYS_KEY_LWIN              91
#define SYS_KEY_RWIN              92
#define SYS_KEY_MENU              93
#define SYS_KEY_PAD               100
#define SYS_KEY_RCONTROL          120
#define SYS_KEY_ALTGR             121
#define SYS_KEY_SLASH2            122
#define SYS_KEY_PAUSE             123

#endif /* _KEYBOARD_H_ */
